# ChessMSWE utilizes the Apache Ant build tool rather than the more modern Gradle/Maven approach. This can be
# observed by finding the build.xml file withou the root of the project. To build the script for Continuous Integration
# the following link was used to get started:

# Source: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: ChessMSWE Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
