# ChessMSWE utilizes the Apache Ant build tool rather than the more modern Gradle/Maven approach. This can be
# observed by finding the build.xml file withou the root of the project. To build the script for Continuous Integration
# the following link was used to get started:

# Sources: 
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant
# https://docs.github.com/en/actions/quickstart
# https://github.com/junit-team/junit4/wiki/Getting-started-–-Ant

name: CI for ChessMSWE

# trigger the pipeline on push regardless of what branch it is
# (feature or master branch)
on: [push]

# running the jobs for this pipeline
jobs:
  # name of the job
  build-project:
    # specify the server OS to use
    runs-on: ubuntu-latest
    steps:
    # Step 1 - Set up JDK 11
    - uses: actions/checkout@v3
    - name: Set up JDK Version 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    # Step 2 - Build the project using Apache Ant. This is based 
    # off of build.xml from the root of the repository
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
